services:
  postgres:
    image: postgres
    container_name: syncr-postgres
    restart: unless-stopped
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: EUdbmy1tdFj5oytL
      POSTGRES_DB: syncr-db
    ports:
      - "5432:5432"
    volumes:
      - syncr-postgres-data:/var/lib/postgresql/docker
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres -d syncr-db"]
      interval: 10s
      timeout: 5s
      retries: 5

  demo-postgres:
    image: postgres
    container_name: syncr-demo-postgres
    restart: unless-stopped
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: EUdbmy1tdFj5oytL
      POSTGRES_DB: syncr-demo-db
    ports:
      - "5433:5432"
    volumes:
      - syncr-demo-postgres-data:/var/lib/postgresql/docker
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres -d syncr-demo-db"]
      interval: 10s
      timeout: 5s
      retries: 5

volumes:
  syncr-postgres-data:
  syncr-demo-postgres-data:

